kind: pipeline
name: default

steps:
- name: publish-tag
  image: plugins/docker
  when:
    event:
      - tag
  settings:
    repo: containers.jasonraimondi.com/jason/twitter-cleaner
    registry: containers.jasonraimondi.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_TAG}
    auto_tag: true
    force_tag: true
